## Deploy application to App Engine
steps:
  - name: "gcr.io/cloud-builders/mvn"
    args: ["clean", "install"]
    dir: "back-end"

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "back-end/app.yaml"]
